
import Codigo.BaseCadastral;
import Codigo.Cliente;
import java.awt.Color;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Bianca e Vítor
 */
public class TelaCadastro extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastro
     */
    public TelaCadastro() {
        initComponents();
        
         getContentPane().setBackground(Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        campoNome = new javax.swing.JTextField();
        campoFone2 = new javax.swing.JTextField();
        campoFone1 = new javax.swing.JTextField();
        campoRua = new javax.swing.JTextField();
        campoCidade = new javax.swing.JTextField();
        campoNumeroCasa = new javax.swing.JTextField();
        campoBairro = new javax.swing.JTextField();
        campoComplemento = new javax.swing.JTextField();
        btnConcluiCadastro = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        campoLogin = new javax.swing.JTextField();
        campoSenha = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        campoConfSenha = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Cadastro");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(340, 20, 106, 29);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Nome*");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(21, 104, 110, 17);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Telefone 1*");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(21, 191, 100, 17);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Telefone 2");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(487, 191, 80, 17);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Bairro*");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 280, 80, 14);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Número*");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(630, 280, 80, 17);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Rua*");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(240, 280, 80, 17);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Cidade*");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(20, 350, 80, 17);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Complemento");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(550, 350, 110, 14);

        campoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNomeActionPerformed(evt);
            }
        });
        getContentPane().add(campoNome);
        campoNome.setBounds(21, 136, 360, 30);

        campoFone2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoFone2ActionPerformed(evt);
            }
        });
        getContentPane().add(campoFone2);
        campoFone2.setBounds(487, 220, 190, 30);

        campoFone1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoFone1ActionPerformed(evt);
            }
        });
        getContentPane().add(campoFone1);
        campoFone1.setBounds(21, 220, 200, 30);
        getContentPane().add(campoRua);
        campoRua.setBounds(240, 300, 250, 30);
        getContentPane().add(campoCidade);
        campoCidade.setBounds(21, 375, 270, 30);

        campoNumeroCasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNumeroCasaActionPerformed(evt);
            }
        });
        getContentPane().add(campoNumeroCasa);
        campoNumeroCasa.setBounds(627, 302, 80, 30);
        getContentPane().add(campoBairro);
        campoBairro.setBounds(21, 302, 190, 30);
        getContentPane().add(campoComplemento);
        campoComplemento.setBounds(553, 375, 160, 30);

        btnConcluiCadastro.setText("Concluir cadastro");
        btnConcluiCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConcluiCadastroActionPerformed(evt);
            }
        });
        getContentPane().add(btnConcluiCadastro);
        btnConcluiCadastro.setBounds(560, 530, 150, 23);

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltar);
        btnVoltar.setBounds(20, 530, 61, 23);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Login*");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 430, 60, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Senha*");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(230, 430, 60, 20);
        getContentPane().add(campoLogin);
        campoLogin.setBounds(21, 464, 160, 30);
        getContentPane().add(campoSenha);
        campoSenha.setBounds(234, 464, 160, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Confirmação da senha*");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(550, 434, 180, 20);
        getContentPane().add(campoConfSenha);
        campoConfSenha.setBounds(553, 464, 150, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo.fw.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        jLabel4.setMaximumSize(new java.awt.Dimension(800, 600));
        jLabel4.setMinimumSize(new java.awt.Dimension(800, 600));
        jLabel4.setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(1, -2, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNomeActionPerformed

    private void campoFone2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoFone2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoFone2ActionPerformed

    private void campoFone1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoFone1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoFone1ActionPerformed

    private void btnConcluiCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConcluiCadastroActionPerformed
        try
        {
            if(confirmaSenha(campoSenha.getText(), campoConfSenha.getText()))
            {
                if(campoFone2.equals(null) && campoComplemento.equals(null)) // caso o usuário não informe o fone2 e o complemento
                {
                    BaseCadastral.getInstance().adicionaCadastro(new Cliente(campoNome.getText(), campoFone1.getText(), campoBairro.getText(), campoRua.getText(), Integer.parseInt(campoNumeroCasa.getText()), campoCidade.getText(), campoLogin.getText(), campoSenha.getText(), campoConfSenha.getText()));
                    JOptionPane.showMessageDialog(this, "Usuário cadastrado");
                    dispose();
                    new TelaInicial().setVisible(true);
                }
            
                else if (campoFone2.equals(null)) // caso o usuário não informe apenas o fone2
                {
                    BaseCadastral.getInstance().adicionaCadastro(new Cliente(campoNome.getText(), campoFone1.getText(), campoBairro.getText(), campoRua.getText(), Integer.parseInt(campoNumeroCasa.getText()), campoCidade.getText(), campoComplemento.getText(), campoLogin.getText(), campoSenha.getText(), campoConfSenha.getText()));
                    JOptionPane.showMessageDialog(this, "Usuário cadastrado");
                    dispose();
                    new TelaInicial().setVisible(true);
                }
            
                else if (campoComplemento.equals(null)) // caso o usuário não informe apenas o complemento
                {
                    BaseCadastral.getInstance().adicionaCadastro(new Cliente(campoNome.getText(), campoFone1.getText(), campoBairro.getText(), campoRua.getText(), Integer.parseInt(campoNumeroCasa.getText()), campoCidade.getText(), campoLogin.getText(), campoSenha.getText(), campoConfSenha.getText()));
                    JOptionPane.showMessageDialog(this, "Usuário cadastrado");
                    dispose();
                    new TelaInicial().setVisible(true); 
                }
            
                else // caso o usuário informe todos os campos
                {
                    BaseCadastral.getInstance().adicionaCadastro(new Cliente(campoNome.getText(), campoFone1.getText(), campoFone2.getText(), campoBairro.getText(), campoRua.getText(), Integer.parseInt(campoNumeroCasa.getText()), campoCidade.getText(), campoComplemento.getText(), campoLogin.getText(), campoSenha.getText(), campoConfSenha.getText()));
                    JOptionPane.showMessageDialog(this, "Usuário cadastrado");
                    dispose();
                    new TelaInicial().setVisible(true);
                }

            }
            
            else
            {
                JOptionPane.showMessageDialog(this, "A senha e a confirmação não conferem. Redigite as duas");
            }

        }
        
        catch (java.lang.NumberFormatException e) // caso algum campo obrigatório não seja preechido
        {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos obrigatórios, os quais possuem *");
        }
            
            
        
    }//GEN-LAST:event_btnConcluiCadastroActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        dispose(); // fecha a janela atual
        new TelaInicial().setVisible(true); // inicia uma nova janela do tipo TelaInicial
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void campoNumeroCasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNumeroCasaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNumeroCasaActionPerformed

    private boolean confirmaSenha(String senha, String confirmacaoSenha)
    {
        return senha.equals(confirmacaoSenha);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConcluiCadastro;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JTextField campoBairro;
    private javax.swing.JTextField campoCidade;
    private javax.swing.JTextField campoComplemento;
    private javax.swing.JPasswordField campoConfSenha;
    private javax.swing.JTextField campoFone1;
    private javax.swing.JTextField campoFone2;
    private javax.swing.JTextField campoLogin;
    private javax.swing.JTextField campoNome;
    private javax.swing.JTextField campoNumeroCasa;
    private javax.swing.JTextField campoRua;
    private javax.swing.JPasswordField campoSenha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
