
import Codigo.EnumSabores;
import Codigo.Pizza;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Vitor
 */
public class TelaSaboresScrollbar extends javax.swing.JFrame {
        
    int precoTamanho = 0;
    /**
     * Creates new form TelaSaboresScrollbar
     */
    public TelaSaboresScrollbar() {
        initComponents();
        //int precoTamanho = 0;
        
        // DEFININDO A QUANTIDADE MÁXIMA DE SABORES
        switch (Pizza.getInstance().getTamanho()) {
            case "Pequena":
                qtdSaboresTotal.setText("1");
                precoTamanho = 4;
                qtdPreco.setText(Integer.toString(precoTamanho));
                break;
            case "Média":
                qtdSaboresTotal.setText("2");
                precoTamanho = 6;
                qtdPreco.setText(Integer.toString(precoTamanho));
                break;
            case "Grande":
                qtdSaboresTotal.setText("3");
                precoTamanho = 8;
                qtdPreco.setText(Integer.toString(precoTamanho));
                break;
            case "Família":
                qtdSaboresTotal.setText("4");
                precoTamanho = 10;
                qtdPreco.setText(Integer.toString(precoTamanho));
                break;
            default:
                break;
        }
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        infTela = new javax.swing.JLabel();
        infPreco = new javax.swing.JLabel();
        qtdPreco = new javax.swing.JLabel();
        infSabores = new javax.swing.JLabel();
        qtdSaboresEscolhidos = new javax.swing.JLabel();
        qtdSaboresTotal = new javax.swing.JLabel();
        BarraAux = new javax.swing.JLabel();
        btnConfirmar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        QuatroQueijos = new javax.swing.JLabel();
        Calabresa = new javax.swing.JLabel();
        infQuatroQueijos = new javax.swing.JLabel();
        infCalabresa = new javax.swing.JLabel();
        qtdCalabresa = new javax.swing.JLabel();
        btnRem4Quejos = new javax.swing.JButton();
        qtd4Queijos = new javax.swing.JLabel();
        btnRemCalabresa = new javax.swing.JButton();
        btnAddCalabresa = new javax.swing.JButton();
        btnAdd4Queijos = new javax.swing.JButton();
        Frango = new javax.swing.JLabel();
        infCamarao = new javax.swing.JLabel();
        btnRemFrango = new javax.swing.JButton();
        qtdFrango = new javax.swing.JLabel();
        btnAddFrango = new javax.swing.JButton();
        Portuguesa = new javax.swing.JLabel();
        infFrango = new javax.swing.JLabel();
        btnRemPortguesa = new javax.swing.JButton();
        qtdPortuguesa = new javax.swing.JLabel();
        btnAddPortuguesa = new javax.swing.JButton();
        Catuperu = new javax.swing.JLabel();
        infPortuguesa = new javax.swing.JLabel();
        btnAddCatuperu = new javax.swing.JButton();
        qtdCatuperu = new javax.swing.JLabel();
        btnRemCatuperu = new javax.swing.JButton();
        Pepperoni = new javax.swing.JLabel();
        infCatuperu = new javax.swing.JLabel();
        btnRemPepperoni = new javax.swing.JButton();
        qtdPepperoni = new javax.swing.JLabel();
        btnAddPepperoni = new javax.swing.JButton();
        Atum = new javax.swing.JLabel();
        infPepperoni = new javax.swing.JLabel();
        btnRemAtum = new javax.swing.JButton();
        qtdAtum = new javax.swing.JLabel();
        btnAddAtum = new javax.swing.JButton();
        FileMignon = new javax.swing.JLabel();
        infAtum = new javax.swing.JLabel();
        btnRemFileMignon = new javax.swing.JButton();
        qtdFileMignon = new javax.swing.JLabel();
        btnAddFileMignon = new javax.swing.JButton();
        Strogonoff = new javax.swing.JLabel();
        infFileMignon = new javax.swing.JLabel();
        btnRemStrogonoff = new javax.swing.JButton();
        qtdSrogonoff = new javax.swing.JLabel();
        btnAddStrogonoff = new javax.swing.JButton();
        Camarao = new javax.swing.JLabel();
        infStrogonoff = new javax.swing.JLabel();
        btnRemCamarao = new javax.swing.JButton();
        qtdCamarao = new javax.swing.JLabel();
        btnAddCamarao = new javax.swing.JButton();
        infCalculoPreco = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        imagemFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        infTela.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        infTela.setText("Selecione os sabores:");
        getContentPane().add(infTela, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        infPreco.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        infPreco.setText("Preço total: R$");
        getContentPane().add(infPreco, new org.netbeans.lib.awtextra.AbsoluteConstraints(594, 14, -1, -1));

        qtdPreco.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        qtdPreco.setText("XX,XX");
        getContentPane().add(qtdPreco, new org.netbeans.lib.awtextra.AbsoluteConstraints(707, 14, 60, -1));

        infSabores.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        infSabores.setText("Sabores escolhidos:");
        getContentPane().add(infSabores, new org.netbeans.lib.awtextra.AbsoluteConstraints(594, 37, -1, -1));

        qtdSaboresEscolhidos.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        qtdSaboresEscolhidos.setText("0");
        getContentPane().add(qtdSaboresEscolhidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 37, 20, -1));

        qtdSaboresTotal.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        qtdSaboresTotal.setText("X");
        getContentPane().add(qtdSaboresTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 37, 20, -1));

        BarraAux.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        BarraAux.setText("/");
        getContentPane().add(BarraAux, new org.netbeans.lib.awtextra.AbsoluteConstraints(756, 37, 10, -1));

        btnConfirmar.setText("Confirmar sabores");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });
        getContentPane().add(btnConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 70, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setPreferredSize(new java.awt.Dimension(800, 1900));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        QuatroQueijos.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        QuatroQueijos.setForeground(new java.awt.Color(0, 153, 0));
        QuatroQueijos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/saborQuatroQueijos.png"))); // NOI18N
        QuatroQueijos.setText("Quatro Queijos - R$ 35,00");
        jPanel2.add(QuatroQueijos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 12, -1, -1));

        Calabresa.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Calabresa.setForeground(new java.awt.Color(0, 153, 0));
        Calabresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/saborCalabresa.png"))); // NOI18N
        Calabresa.setText("Calabresa - R$ 35,00");
        jPanel2.add(Calabresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        infQuatroQueijos.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        infQuatroQueijos.setText("Mussarela, provolone, parmesão e gorgonzola");
        jPanel2.add(infQuatroQueijos, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 112, 380, -1));

        infCalabresa.setBackground(new java.awt.Color(153, 153, 153));
        infCalabresa.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        infCalabresa.setForeground(new java.awt.Color(51, 51, 51));
        infCalabresa.setText("Mussarela, calabresa e cebola");
        jPanel2.add(infCalabresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 278, 250, -1));

        qtdCalabresa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        qtdCalabresa.setText("0");
        jPanel2.add(qtdCalabresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(676, 278, -1, -1));

        btnRem4Quejos.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnRem4Quejos.setForeground(new java.awt.Color(255, 0, 51));
        btnRem4Quejos.setText("-");
        btnRem4Quejos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRem4QuejosActionPerformed(evt);
            }
        });
        jPanel2.add(btnRem4Quejos, new org.netbeans.lib.awtextra.AbsoluteConstraints(596, 95, 50, -1));

        qtd4Queijos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        qtd4Queijos.setText("0");
        qtd4Queijos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.add(qtd4Queijos, new org.netbeans.lib.awtextra.AbsoluteConstraints(676, 105, -1, -1));

        btnRemCalabresa.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnRemCalabresa.setForeground(new java.awt.Color(255, 0, 51));
        btnRemCalabresa.setText("-");
        btnRemCalabresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemCalabresaActionPerformed(evt);
            }
        });
        jPanel2.add(btnRemCalabresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(596, 264, 50, -1));

        btnAddCalabresa.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnAddCalabresa.setForeground(new java.awt.Color(0, 153, 51));
        btnAddCalabresa.setText("+");
        btnAddCalabresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCalabresaActionPerformed(evt);
            }
        });
        jPanel2.add(btnAddCalabresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(716, 264, -1, -1));

        btnAdd4Queijos.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnAdd4Queijos.setForeground(new java.awt.Color(0, 153, 51));
        btnAdd4Queijos.setText("+");
        btnAdd4Queijos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd4QueijosActionPerformed(evt);
            }
        });
        jPanel2.add(btnAdd4Queijos, new org.netbeans.lib.awtextra.AbsoluteConstraints(716, 95, -1, -1));

        Frango.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Frango.setForeground(new java.awt.Color(0, 153, 0));
        Frango.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/saborFrango.png"))); // NOI18N
        Frango.setText("Frango - R$ 35,00");
        jPanel2.add(Frango, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 340, -1));

        infCamarao.setBackground(new java.awt.Color(153, 153, 153));
        infCamarao.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        infCamarao.setForeground(new java.awt.Color(51, 51, 51));
        infCamarao.setText("Mussarela, camarão e parmesão.");
        jPanel2.add(infCamarao, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 1770, 420, 60));

        btnRemFrango.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnRemFrango.setForeground(new java.awt.Color(255, 0, 51));
        btnRemFrango.setText("-");
        btnRemFrango.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemFrangoActionPerformed(evt);
            }
        });
        jPanel2.add(btnRemFrango, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 440, 50, -1));

        qtdFrango.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        qtdFrango.setText("0");
        jPanel2.add(qtdFrango, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 450, -1, -1));

        btnAddFrango.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnAddFrango.setForeground(new java.awt.Color(0, 153, 51));
        btnAddFrango.setText("+");
        btnAddFrango.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFrangoActionPerformed(evt);
            }
        });
        jPanel2.add(btnAddFrango, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 440, -1, -1));

        Portuguesa.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Portuguesa.setForeground(new java.awt.Color(0, 153, 0));
        Portuguesa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/saborPortuguesa.png"))); // NOI18N
        Portuguesa.setText("Portuguesa - R$ 35,00");
        jPanel2.add(Portuguesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, -1, -1));

        infFrango.setBackground(new java.awt.Color(153, 153, 153));
        infFrango.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        infFrango.setForeground(new java.awt.Color(51, 51, 51));
        infFrango.setText("Mussarela, frango desfiado e requeijão catupiry");
        jPanel2.add(infFrango, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 460, 410, -1));

        btnRemPortguesa.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnRemPortguesa.setForeground(new java.awt.Color(255, 0, 51));
        btnRemPortguesa.setText("-");
        btnRemPortguesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemPortguesaActionPerformed(evt);
            }
        });
        jPanel2.add(btnRemPortguesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 610, 50, -1));

        qtdPortuguesa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        qtdPortuguesa.setText("0");
        jPanel2.add(qtdPortuguesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 620, -1, -1));

        btnAddPortuguesa.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnAddPortuguesa.setForeground(new java.awt.Color(0, 153, 51));
        btnAddPortuguesa.setText("+");
        btnAddPortuguesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPortuguesaActionPerformed(evt);
            }
        });
        jPanel2.add(btnAddPortuguesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 610, -1, -1));

        Catuperu.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Catuperu.setForeground(new java.awt.Color(0, 153, 0));
        Catuperu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/saborCatuperu.png"))); // NOI18N
        Catuperu.setText("Catuperu - R$ 40,00");
        jPanel2.add(Catuperu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 730, -1, -1));

        infPortuguesa.setBackground(new java.awt.Color(153, 153, 153));
        infPortuguesa.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        infPortuguesa.setForeground(new java.awt.Color(51, 51, 51));
        infPortuguesa.setText("Mussarela, cebola, presunto e ovos");
        jPanel2.add(infPortuguesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 640, 380, -1));

        btnAddCatuperu.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnAddCatuperu.setForeground(new java.awt.Color(0, 153, 51));
        btnAddCatuperu.setText("+");
        btnAddCatuperu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCatuperuActionPerformed(evt);
            }
        });
        jPanel2.add(btnAddCatuperu, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 810, -1, -1));

        qtdCatuperu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        qtdCatuperu.setText("0");
        jPanel2.add(qtdCatuperu, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 820, -1, -1));

        btnRemCatuperu.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnRemCatuperu.setForeground(new java.awt.Color(255, 0, 51));
        btnRemCatuperu.setText("-");
        btnRemCatuperu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemCatuperuActionPerformed(evt);
            }
        });
        jPanel2.add(btnRemCatuperu, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 810, 50, -1));

        Pepperoni.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Pepperoni.setForeground(new java.awt.Color(0, 153, 0));
        Pepperoni.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/saborPepperoni.png"))); // NOI18N
        Pepperoni.setText("Pepperoni - R$ 40,00");
        jPanel2.add(Pepperoni, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 910, -1, -1));

        infCatuperu.setBackground(new java.awt.Color(153, 153, 153));
        infCatuperu.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        infCatuperu.setForeground(new java.awt.Color(51, 51, 51));
        infCatuperu.setText("Mussarela, peito de peru defumado e catupiry");
        jPanel2.add(infCatuperu, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 830, 380, -1));

        btnRemPepperoni.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnRemPepperoni.setForeground(new java.awt.Color(255, 0, 51));
        btnRemPepperoni.setText("-");
        btnRemPepperoni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemPepperoniActionPerformed(evt);
            }
        });
        jPanel2.add(btnRemPepperoni, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 980, 50, -1));

        qtdPepperoni.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        qtdPepperoni.setText("0");
        jPanel2.add(qtdPepperoni, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 990, -1, -1));

        btnAddPepperoni.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnAddPepperoni.setForeground(new java.awt.Color(0, 153, 51));
        btnAddPepperoni.setText("+");
        btnAddPepperoni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPepperoniActionPerformed(evt);
            }
        });
        jPanel2.add(btnAddPepperoni, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 980, -1, -1));

        Atum.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Atum.setForeground(new java.awt.Color(0, 153, 0));
        Atum.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/saborAtum.png"))); // NOI18N
        Atum.setText("Atum - R$ 40,00");
        jPanel2.add(Atum, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 1100, -1, -1));

        infPepperoni.setBackground(new java.awt.Color(153, 153, 153));
        infPepperoni.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        infPepperoni.setForeground(new java.awt.Color(51, 51, 51));
        infPepperoni.setText("Mussarela e pepperoni.");
        jPanel2.add(infPepperoni, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 1010, 380, -1));

        btnRemAtum.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnRemAtum.setForeground(new java.awt.Color(255, 0, 51));
        btnRemAtum.setText("-");
        btnRemAtum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemAtumActionPerformed(evt);
            }
        });
        jPanel2.add(btnRemAtum, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 1170, 50, -1));

        qtdAtum.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        qtdAtum.setText("0");
        jPanel2.add(qtdAtum, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 1180, -1, -1));

        btnAddAtum.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnAddAtum.setForeground(new java.awt.Color(0, 153, 51));
        btnAddAtum.setText("+");
        btnAddAtum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAtumActionPerformed(evt);
            }
        });
        jPanel2.add(btnAddAtum, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 1170, -1, -1));

        FileMignon.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        FileMignon.setForeground(new java.awt.Color(0, 153, 0));
        FileMignon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/saborFileMignon.png"))); // NOI18N
        FileMignon.setText("Filé Mignon - RS 48,00");
        jPanel2.add(FileMignon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 1300, -1, -1));

        infAtum.setBackground(new java.awt.Color(153, 153, 153));
        infAtum.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        infAtum.setForeground(new java.awt.Color(51, 51, 51));
        infAtum.setText("Mussarela, atum e cebola");
        jPanel2.add(infAtum, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 1200, 380, -1));

        btnRemFileMignon.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnRemFileMignon.setForeground(new java.awt.Color(255, 0, 51));
        btnRemFileMignon.setText("-");
        btnRemFileMignon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemFileMignonActionPerformed(evt);
            }
        });
        jPanel2.add(btnRemFileMignon, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 1370, 50, -1));

        qtdFileMignon.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        qtdFileMignon.setText("0");
        jPanel2.add(qtdFileMignon, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 1380, -1, -1));

        btnAddFileMignon.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnAddFileMignon.setForeground(new java.awt.Color(0, 153, 51));
        btnAddFileMignon.setText("+");
        btnAddFileMignon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFileMignonActionPerformed(evt);
            }
        });
        jPanel2.add(btnAddFileMignon, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 1370, -1, -1));

        Strogonoff.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Strogonoff.setForeground(new java.awt.Color(0, 153, 0));
        Strogonoff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/saborStrogonoff.png"))); // NOI18N
        Strogonoff.setText("Strogonoff - R$ 48,00");
        jPanel2.add(Strogonoff, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 1490, -1, -1));

        infFileMignon.setBackground(new java.awt.Color(153, 153, 153));
        infFileMignon.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        infFileMignon.setForeground(new java.awt.Color(51, 51, 51));
        infFileMignon.setText("Mussarela, filé mignon e requeijão catupiry");
        jPanel2.add(infFileMignon, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 1400, 380, -1));

        btnRemStrogonoff.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnRemStrogonoff.setForeground(new java.awt.Color(255, 0, 51));
        btnRemStrogonoff.setText("-");
        btnRemStrogonoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemStrogonoffActionPerformed(evt);
            }
        });
        jPanel2.add(btnRemStrogonoff, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 1580, 50, -1));

        qtdSrogonoff.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        qtdSrogonoff.setText("0");
        jPanel2.add(qtdSrogonoff, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 1590, -1, -1));

        btnAddStrogonoff.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnAddStrogonoff.setForeground(new java.awt.Color(0, 153, 51));
        btnAddStrogonoff.setText("+");
        btnAddStrogonoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddStrogonoffActionPerformed(evt);
            }
        });
        jPanel2.add(btnAddStrogonoff, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 1580, -1, -1));

        Camarao.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Camarao.setForeground(new java.awt.Color(0, 153, 0));
        Camarao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/saborCamarao.png"))); // NOI18N
        Camarao.setText("Camarão - R$ 48,00");
        jPanel2.add(Camarao, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 1690, -1, -1));

        infStrogonoff.setBackground(new java.awt.Color(153, 153, 153));
        infStrogonoff.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        infStrogonoff.setForeground(new java.awt.Color(51, 51, 51));
        infStrogonoff.setText("Mussarela, strogonoff de filet mignon, champingon e batata palha");
        jPanel2.add(infStrogonoff, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 1570, 420, 60));

        btnRemCamarao.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnRemCamarao.setForeground(new java.awt.Color(255, 0, 51));
        btnRemCamarao.setText("-");
        btnRemCamarao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemCamaraoActionPerformed(evt);
            }
        });
        jPanel2.add(btnRemCamarao, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 1770, 50, -1));

        qtdCamarao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        qtdCamarao.setText("0");
        jPanel2.add(qtdCamarao, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 1780, -1, -1));

        btnAddCamarao.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnAddCamarao.setForeground(new java.awt.Color(0, 153, 51));
        btnAddCamarao.setText("+");
        btnAddCamarao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCamaraoActionPerformed(evt);
            }
        });
        jPanel2.add(btnAddCamarao, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 1770, -1, -1));

        jScrollPane1.setViewportView(jPanel2);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 800, 500));

        infCalculoPreco.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        infCalculoPreco.setText("Cálculo do preço: (Preço total dos sabores escolhidos / número de sabores escolhidos) + preco do tamanho");
        getContentPane().add(infCalculoPreco, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel1.setText("Obs: Valores quebrados SEMPRE serão arredondados para baixo");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        imagemFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo1.fw.png"))); // NOI18N
        imagemFundo.setText("jLabel2");
        getContentPane().add(imagemFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        if(qtdSaboresEscolhidos.getText().equals(qtdSaboresTotal.getText()))
        {
            Pizza.getInstance().setPreco(Integer.parseInt(qtdPreco.getText()));
            dispose();
            new TelaBebidas().setVisible(true);            
        }
      
        else
        {
            JOptionPane.showMessageDialog(null, "Informe todos os sabores");
        }

    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnRem4QuejosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRem4QuejosActionPerformed
        
        int somador = Integer.parseInt(qtd4Queijos.getText()); // cria variável para converter para inteiro
        
        
            try
            {
                if(Integer.parseInt(qtdSaboresEscolhidos.getText()) > 0 && somador > 0)
                {
                    Pizza.getInstance().getSabores().remove(EnumSabores.QUATROQUEIJOS);
                    somador--;
                    qtdSaboresEscolhidos.setText(Integer.toString(Integer.parseInt(qtdSaboresEscolhidos.getText()) - 1));
                    qtd4Queijos.setText(Integer.toString(somador)); // devolve valor correto para a váriavel de origem, convertido em String
                    qtdPreco.setText(Integer.toString(Pizza.getInstance().calculaPreco() + precoTamanho));
                }                   
            }
            
            catch(java.lang.ArithmeticException a)
            {
                qtdPreco.setText(Integer.toString(precoTamanho));
            }
        
        //System.out.println(Pizza.getInstance().getSabores());
    }//GEN-LAST:event_btnRem4QuejosActionPerformed

    private void btnAdd4QueijosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd4QueijosActionPerformed
        
        int somador = Integer.parseInt(qtd4Queijos.getText());

        if(Integer.parseInt(qtdSaboresEscolhidos.getText()) < Integer.parseInt(qtdSaboresTotal.getText()))
        {
            Pizza.getInstance().getSabores().add(EnumSabores.QUATROQUEIJOS);
            somador++;
            qtdSaboresEscolhidos.setText(Integer.toString(Integer.parseInt(qtdSaboresEscolhidos.getText()) + 1));
            qtd4Queijos.setText(Integer.toString(somador));
            qtdPreco.setText(Integer.toString(Pizza.getInstance().calculaPreco() + precoTamanho));
        
        }
               

        //System.out.println(Pizza.getInstance().getSabores());
    }//GEN-LAST:event_btnAdd4QueijosActionPerformed

    private void btnRemCatuperuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemCatuperuActionPerformed
        int somador = Integer.parseInt(qtdCatuperu.getText()); // cria variável para converter para inteiro
        
        try
        {
            if(Integer.parseInt(qtdSaboresEscolhidos.getText()) > 0 && somador > 0)
            {
                Pizza.getInstance().getSabores().remove(EnumSabores.CATUPERU);
                somador--;
                qtdSaboresEscolhidos.setText(Integer.toString(Integer.parseInt(qtdSaboresEscolhidos.getText()) - 1));
                qtdCatuperu.setText(Integer.toString(somador)); // devolve valor correto para a váriavel de origem, convertido em String
                qtdPreco.setText(Integer.toString(Pizza.getInstance().calculaPreco() + precoTamanho));
            }            
        }
        
        catch(java.lang.ArithmeticException a)
        {
            qtdPreco.setText(Integer.toString(precoTamanho));
        }
        
        //System.out.println(Pizza.getInstance().getSabores());
    }//GEN-LAST:event_btnRemCatuperuActionPerformed

    private void btnRemFrangoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemFrangoActionPerformed
        int somador = Integer.parseInt(qtdFrango.getText()); // cria variável para converter para inteiro
        
        try
        {
            if(Integer.parseInt(qtdSaboresEscolhidos.getText()) > 0 && somador > 0)
            {
                Pizza.getInstance().getSabores().remove(EnumSabores.FRANGO);
                somador--;
                qtdSaboresEscolhidos.setText(Integer.toString(Integer.parseInt(qtdSaboresEscolhidos.getText()) - 1));
                qtdFrango.setText(Integer.toString(somador)); // devolve valor correto para a váriavel de origem, convertido em String
                qtdPreco.setText(Integer.toString(Pizza.getInstance().calculaPreco() + precoTamanho));
            }            
        }
        
        catch(java.lang.ArithmeticException a)
        {
            qtdPreco.setText(Integer.toString(precoTamanho));
        }
        
        //System.out.println(Pizza.getInstance().getSabores());
    }//GEN-LAST:event_btnRemFrangoActionPerformed

    private void btnRemCalabresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemCalabresaActionPerformed
        
        int somador = Integer.parseInt(qtdCalabresa.getText()); // cria variável para converter para inteiro
        
        try
        {
            if(Integer.parseInt(qtdSaboresEscolhidos.getText()) > 0 && somador > 0)
            {
                Pizza.getInstance().getSabores().remove(EnumSabores.CALABRESA);
                somador--;
                qtdSaboresEscolhidos.setText(Integer.toString(Integer.parseInt(qtdSaboresEscolhidos.getText()) - 1));
                qtdCalabresa.setText(Integer.toString(somador)); // devolve valor correto para a váriavel de origem, convertido em String
                qtdPreco.setText(Integer.toString(Pizza.getInstance().calculaPreco() + precoTamanho));
            }                    
        }

        catch(java.lang.ArithmeticException a)
        {
            qtdPreco.setText(Integer.toString(precoTamanho));
        }   

        //System.out.println(Pizza.getInstance().getSabores());

    }//GEN-LAST:event_btnRemCalabresaActionPerformed

    private void btnAddCalabresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCalabresaActionPerformed
        
        int somador = Integer.parseInt(qtdCalabresa.getText());
        
        
        if(Integer.parseInt(qtdSaboresEscolhidos.getText()) < Integer.parseInt(qtdSaboresTotal.getText()))
        {
            Pizza.getInstance().getSabores().add(EnumSabores.CALABRESA);
            if(somador < Integer.parseInt(qtdSaboresTotal.getText()))
            {
                somador++;
                qtdSaboresEscolhidos.setText(Integer.toString(Integer.parseInt(qtdSaboresEscolhidos.getText()) + 1));
                qtdCalabresa.setText(Integer.toString(somador));
                qtdPreco.setText(Integer.toString(Pizza.getInstance().calculaPreco() + precoTamanho));
            }
        }

        //System.out.println(Pizza.getInstance().getSabores());
        
    }//GEN-LAST:event_btnAddCalabresaActionPerformed

    private void btnAddFrangoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFrangoActionPerformed
        int somador = Integer.parseInt(qtdFrango.getText());

        if(Integer.parseInt(qtdSaboresEscolhidos.getText()) < Integer.parseInt(qtdSaboresTotal.getText()))
        {
            Pizza.getInstance().getSabores().add(EnumSabores.FRANGO);
            somador++;
            qtdSaboresEscolhidos.setText(Integer.toString(Integer.parseInt(qtdSaboresEscolhidos.getText()) + 1));
            qtdFrango.setText(Integer.toString(somador));
            qtdPreco.setText(Integer.toString(Pizza.getInstance().calculaPreco() + precoTamanho));
        
        }
        
        //System.out.println(Pizza.getInstance().getSabores());
    }//GEN-LAST:event_btnAddFrangoActionPerformed

    private void btnAddPortuguesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPortuguesaActionPerformed
        int somador = Integer.parseInt(qtdPortuguesa.getText());

        if(Integer.parseInt(qtdSaboresEscolhidos.getText()) < Integer.parseInt(qtdSaboresTotal.getText()))
        {
            Pizza.getInstance().getSabores().add(EnumSabores.PORTUGUESA);
            somador++;
            qtdSaboresEscolhidos.setText(Integer.toString(Integer.parseInt(qtdSaboresEscolhidos.getText()) + 1));
            qtdPortuguesa.setText(Integer.toString(somador));
            qtdPreco.setText(Integer.toString(Pizza.getInstance().calculaPreco() + precoTamanho));
        
        }
        
        //System.out.println(Pizza.getInstance().getSabores());
    }//GEN-LAST:event_btnAddPortuguesaActionPerformed

    private void btnRemPortguesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemPortguesaActionPerformed
        int somador = Integer.parseInt(qtdPortuguesa.getText()); // cria variável para converter para inteiro
        
        try
        {
            if(Integer.parseInt(qtdSaboresEscolhidos.getText()) > 0 && somador > 0)
            {
                Pizza.getInstance().getSabores().remove(EnumSabores.PORTUGUESA);
                somador--;
                qtdSaboresEscolhidos.setText(Integer.toString(Integer.parseInt(qtdSaboresEscolhidos.getText()) - 1));
                qtdPortuguesa.setText(Integer.toString(somador)); // devolve valor correto para a váriavel de origem, convertido em String
                qtdPreco.setText(Integer.toString(Pizza.getInstance().calculaPreco() + precoTamanho));
            }            
        }
        
        catch(java.lang.ArithmeticException a)
        {
            qtdPreco.setText(Integer.toString(precoTamanho));
        }
        
        //System.out.println(Pizza.getInstance().getSabores());
    }//GEN-LAST:event_btnRemPortguesaActionPerformed

    private void btnAddCatuperuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCatuperuActionPerformed
        int somador = Integer.parseInt(qtdCatuperu.getText());

        if(Integer.parseInt(qtdSaboresEscolhidos.getText()) < Integer.parseInt(qtdSaboresTotal.getText()))
        {
            Pizza.getInstance().getSabores().add(EnumSabores.CATUPERU);
            somador++;
            qtdSaboresEscolhidos.setText(Integer.toString(Integer.parseInt(qtdSaboresEscolhidos.getText()) + 1));
            qtdCatuperu.setText(Integer.toString(somador));
            qtdPreco.setText(Integer.toString(Pizza.getInstance().calculaPreco() + precoTamanho));
        
        }
        
        //System.out.println(Pizza.getInstance().getSabores());
    }//GEN-LAST:event_btnAddCatuperuActionPerformed

    private void btnAddPepperoniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPepperoniActionPerformed
        int somador = Integer.parseInt(qtdPepperoni.getText());

        if(Integer.parseInt(qtdSaboresEscolhidos.getText()) < Integer.parseInt(qtdSaboresTotal.getText()))
        {
            Pizza.getInstance().getSabores().add(EnumSabores.PEPPERONI);
            somador++;
            qtdSaboresEscolhidos.setText(Integer.toString(Integer.parseInt(qtdSaboresEscolhidos.getText()) + 1));
            qtdPepperoni.setText(Integer.toString(somador));
            qtdPreco.setText(Integer.toString(Pizza.getInstance().calculaPreco() + precoTamanho));
        
        }
        
        //System.out.println(Pizza.getInstance().getSabores());
    }//GEN-LAST:event_btnAddPepperoniActionPerformed

    private void btnRemPepperoniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemPepperoniActionPerformed
        int somador = Integer.parseInt(qtdPepperoni.getText()); // cria variável para converter para inteiro
        
        try
        {
            if(Integer.parseInt(qtdSaboresEscolhidos.getText()) > 0 && somador > 0)
            {
                Pizza.getInstance().getSabores().remove(EnumSabores.PEPPERONI);
                somador--;
                qtdSaboresEscolhidos.setText(Integer.toString(Integer.parseInt(qtdSaboresEscolhidos.getText()) - 1));
                qtdPepperoni.setText(Integer.toString(somador)); // devolve valor correto para a váriavel de origem, convertido em String
                qtdPreco.setText(Integer.toString(Pizza.getInstance().calculaPreco() + precoTamanho));
            }            
        }
        
        catch(java.lang.ArithmeticException a)
        {
            qtdPreco.setText(Integer.toString(precoTamanho));
        }
        
        //System.out.println(Pizza.getInstance().getSabores());
    }//GEN-LAST:event_btnRemPepperoniActionPerformed

    private void btnAddAtumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAtumActionPerformed
        int somador = Integer.parseInt(qtdAtum.getText());

        if(Integer.parseInt(qtdSaboresEscolhidos.getText()) < Integer.parseInt(qtdSaboresTotal.getText()))
        {
            Pizza.getInstance().getSabores().add(EnumSabores.ATUM);
            somador++;
            qtdSaboresEscolhidos.setText(Integer.toString(Integer.parseInt(qtdSaboresEscolhidos.getText()) + 1));
            qtdAtum.setText(Integer.toString(somador));
            qtdPreco.setText(Integer.toString(Pizza.getInstance().calculaPreco() + precoTamanho));
        
        }
        
        //System.out.println(Pizza.getInstance().getSabores());
    }//GEN-LAST:event_btnAddAtumActionPerformed

    private void btnRemAtumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemAtumActionPerformed
        int somador = Integer.parseInt(qtdAtum.getText()); // cria variável para converter para inteiro
        
        try
        {
            if(Integer.parseInt(qtdSaboresEscolhidos.getText()) > 0 && somador > 0)
            {
                Pizza.getInstance().getSabores().remove(EnumSabores.ATUM);
                somador--;
                qtdSaboresEscolhidos.setText(Integer.toString(Integer.parseInt(qtdSaboresEscolhidos.getText()) - 1));
                qtdAtum.setText(Integer.toString(somador)); // devolve valor correto para a váriavel de origem, convertido em String
                qtdPreco.setText(Integer.toString(Pizza.getInstance().calculaPreco() + precoTamanho));
            }            
        }
        
        catch(java.lang.ArithmeticException a)
        {
            qtdPreco.setText(Integer.toString(precoTamanho));
        }
        
        //System.out.println(Pizza.getInstance().getSabores());
    }//GEN-LAST:event_btnRemAtumActionPerformed

    private void btnAddFileMignonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFileMignonActionPerformed
        int somador = Integer.parseInt(qtdFileMignon.getText());

        if(Integer.parseInt(qtdSaboresEscolhidos.getText()) < Integer.parseInt(qtdSaboresTotal.getText()))
        {
            Pizza.getInstance().getSabores().add(EnumSabores.FILEMIGNON);
            somador++;
            qtdSaboresEscolhidos.setText(Integer.toString(Integer.parseInt(qtdSaboresEscolhidos.getText()) + 1));
            qtdFileMignon.setText(Integer.toString(somador));
            qtdPreco.setText(Integer.toString(Pizza.getInstance().calculaPreco() + precoTamanho));
        
        }
        
        //System.out.println(Pizza.getInstance().getSabores());
    }//GEN-LAST:event_btnAddFileMignonActionPerformed

    private void btnRemFileMignonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemFileMignonActionPerformed
        int somador = Integer.parseInt(qtdFileMignon.getText()); // cria variável para converter para inteiro
        
        try
        {
            if(Integer.parseInt(qtdSaboresEscolhidos.getText()) > 0 && somador > 0)
            {
                Pizza.getInstance().getSabores().remove(EnumSabores.FILEMIGNON);
                somador--;
                qtdSaboresEscolhidos.setText(Integer.toString(Integer.parseInt(qtdSaboresEscolhidos.getText()) - 1));
                qtdFileMignon.setText(Integer.toString(somador)); // devolve valor correto para a váriavel de origem, convertido em String
                qtdPreco.setText(Integer.toString(Pizza.getInstance().calculaPreco() + precoTamanho));
            }            
        }
        
        catch(java.lang.ArithmeticException a)
        {
            qtdPreco.setText(Integer.toString(precoTamanho));
        }
        
        //System.out.println(Pizza.getInstance().getSabores());
    }//GEN-LAST:event_btnRemFileMignonActionPerformed

    private void btnAddStrogonoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStrogonoffActionPerformed
        int somador = Integer.parseInt(qtdSrogonoff.getText());

        if(Integer.parseInt(qtdSaboresEscolhidos.getText()) < Integer.parseInt(qtdSaboresTotal.getText()))
        {
            Pizza.getInstance().getSabores().add(EnumSabores.STROGONOFF);
            somador++;
            qtdSaboresEscolhidos.setText(Integer.toString(Integer.parseInt(qtdSaboresEscolhidos.getText()) + 1));
            qtdSrogonoff.setText(Integer.toString(somador));
            qtdPreco.setText(Integer.toString(Pizza.getInstance().calculaPreco() + precoTamanho));
        
        }
        
        //System.out.println(Pizza.getInstance().getSabores());
    }//GEN-LAST:event_btnAddStrogonoffActionPerformed

    private void btnRemStrogonoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemStrogonoffActionPerformed
        int somador = Integer.parseInt(qtdSrogonoff.getText()); // cria variável para converter para inteiro
        
        try
        {
            if(Integer.parseInt(qtdSaboresEscolhidos.getText()) > 0 && somador > 0)
            {
                Pizza.getInstance().getSabores().remove(EnumSabores.STROGONOFF);
                somador--;
                qtdSaboresEscolhidos.setText(Integer.toString(Integer.parseInt(qtdSaboresEscolhidos.getText()) - 1));
                qtdSrogonoff.setText(Integer.toString(somador)); // devolve valor correto para a váriavel de origem, convertido em String
                qtdPreco.setText(Integer.toString(Pizza.getInstance().calculaPreco() + precoTamanho));
            }            
        }
        
        catch(java.lang.ArithmeticException a)
        {
            qtdPreco.setText(Integer.toString(precoTamanho));
        }
        
        //System.out.println(Pizza.getInstance().getSabores());
    }//GEN-LAST:event_btnRemStrogonoffActionPerformed

    private void btnAddCamaraoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCamaraoActionPerformed
        int somador = Integer.parseInt(qtdCamarao.getText());

        if(Integer.parseInt(qtdSaboresEscolhidos.getText()) < Integer.parseInt(qtdSaboresTotal.getText()))
        {
            Pizza.getInstance().getSabores().add(EnumSabores.CAMARAO);
            somador++;
            qtdSaboresEscolhidos.setText(Integer.toString(Integer.parseInt(qtdSaboresEscolhidos.getText()) + 1));
            qtdCamarao.setText(Integer.toString(somador));
            qtdPreco.setText(Integer.toString(Pizza.getInstance().calculaPreco() + precoTamanho));
        
        }
        
        //System.out.println(Pizza.getInstance().getSabores());
    }//GEN-LAST:event_btnAddCamaraoActionPerformed

    private void btnRemCamaraoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemCamaraoActionPerformed
        int somador = Integer.parseInt(qtdCamarao.getText()); // cria variável para converter para inteiro
        
        try
        {
            if(Integer.parseInt(qtdSaboresEscolhidos.getText()) > 0 && somador > 0)
            {
                Pizza.getInstance().getSabores().remove(EnumSabores.CAMARAO);
                somador--;
                qtdSaboresEscolhidos.setText(Integer.toString(Integer.parseInt(qtdSaboresEscolhidos.getText()) - 1));
                qtdCamarao.setText(Integer.toString(somador)); // devolve valor correto para a váriavel de origem, convertido em String
                qtdPreco.setText(Integer.toString(Pizza.getInstance().calculaPreco() + precoTamanho));
            }            
        }
        
        catch(java.lang.ArithmeticException a)
        {
            qtdPreco.setText(Integer.toString(precoTamanho));
        }
        
        //System.out.println(Pizza.getInstance().getSabores());
    }//GEN-LAST:event_btnRemCamaraoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaSaboresScrollbar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaSaboresScrollbar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaSaboresScrollbar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaSaboresScrollbar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaSaboresScrollbar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Atum;
    private javax.swing.JLabel BarraAux;
    private javax.swing.JLabel Calabresa;
    private javax.swing.JLabel Camarao;
    private javax.swing.JLabel Catuperu;
    private javax.swing.JLabel FileMignon;
    private javax.swing.JLabel Frango;
    private javax.swing.JLabel Pepperoni;
    private javax.swing.JLabel Portuguesa;
    private javax.swing.JLabel QuatroQueijos;
    private javax.swing.JLabel Strogonoff;
    private javax.swing.JButton btnAdd4Queijos;
    private javax.swing.JButton btnAddAtum;
    private javax.swing.JButton btnAddCalabresa;
    private javax.swing.JButton btnAddCamarao;
    private javax.swing.JButton btnAddCatuperu;
    private javax.swing.JButton btnAddFileMignon;
    private javax.swing.JButton btnAddFrango;
    private javax.swing.JButton btnAddPepperoni;
    private javax.swing.JButton btnAddPortuguesa;
    private javax.swing.JButton btnAddStrogonoff;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnRem4Quejos;
    private javax.swing.JButton btnRemAtum;
    private javax.swing.JButton btnRemCalabresa;
    private javax.swing.JButton btnRemCamarao;
    private javax.swing.JButton btnRemCatuperu;
    private javax.swing.JButton btnRemFileMignon;
    private javax.swing.JButton btnRemFrango;
    private javax.swing.JButton btnRemPepperoni;
    private javax.swing.JButton btnRemPortguesa;
    private javax.swing.JButton btnRemStrogonoff;
    private javax.swing.JLabel imagemFundo;
    private javax.swing.JLabel infAtum;
    private javax.swing.JLabel infCalabresa;
    private javax.swing.JLabel infCalculoPreco;
    private javax.swing.JLabel infCamarao;
    private javax.swing.JLabel infCatuperu;
    private javax.swing.JLabel infFileMignon;
    private javax.swing.JLabel infFrango;
    private javax.swing.JLabel infPepperoni;
    private javax.swing.JLabel infPortuguesa;
    private javax.swing.JLabel infPreco;
    private javax.swing.JLabel infQuatroQueijos;
    private javax.swing.JLabel infSabores;
    private javax.swing.JLabel infStrogonoff;
    private javax.swing.JLabel infTela;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel qtd4Queijos;
    private javax.swing.JLabel qtdAtum;
    private javax.swing.JLabel qtdCalabresa;
    private javax.swing.JLabel qtdCamarao;
    private javax.swing.JLabel qtdCatuperu;
    private javax.swing.JLabel qtdFileMignon;
    private javax.swing.JLabel qtdFrango;
    private javax.swing.JLabel qtdPepperoni;
    private javax.swing.JLabel qtdPortuguesa;
    private javax.swing.JLabel qtdPreco;
    private javax.swing.JLabel qtdSaboresEscolhidos;
    private javax.swing.JLabel qtdSaboresTotal;
    private javax.swing.JLabel qtdSrogonoff;
    // End of variables declaration//GEN-END:variables
}
