
import Codigo.Carrinho;
import Codigo.Pizza;
import java.awt.Image;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Bianca
 */
public class TelaFinal extends javax.swing.JFrame {

    /**
     * Creates new form TelaFinal
     */
    public TelaFinal() {
        initComponents();
        
        ImageIcon imageIntro = new ImageIcon(TelaInicial.class.getResource("/imagens/moto.png"));
        Image img = imageIntro.getImage().getScaledInstance((80*3), (74*3), Image.SCALE_SMOOTH);
        imagemFinal.setIcon(new ImageIcon(img));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnOutroPedido = new javax.swing.JButton();
        msgFinal = new javax.swing.JLabel();
        imagemFinal = new javax.swing.JLabel();
        imagemFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        btnOutroPedido.setText("Realizar Outro Pedido");
        btnOutroPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOutroPedidoActionPerformed(evt);
            }
        });
        getContentPane().add(btnOutroPedido);
        btnOutroPedido.setBounds(280, 510, 210, 23);

        msgFinal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        msgFinal.setText("Seu pedido está a caminho...");
        getContentPane().add(msgFinal);
        msgFinal.setBounds(230, 70, 510, 50);
        getContentPane().add(imagemFinal);
        imagemFinal.setBounds(280, 150, 330, 260);

        imagemFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo.fw.png"))); // NOI18N
        imagemFundo.setText("Fundo");
        getContentPane().add(imagemFundo);
        imagemFundo.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOutroPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOutroPedidoActionPerformed
        
        Pizza.getInstance().setObservacoes(null);
        Pizza.getInstance().setPreco(0);
        Pizza.getInstance().getSabores().clear();
        Pizza.getInstance().setTipoBorda(null);
        Pizza.getInstance().getAdicionais().clear();
        
        Carrinho.getInstance().setPagamento(null);
        Carrinho.getInstance().setPrecoTotal(0);
        
        dispose(); // fecha a tela atual
        new TelaTamanhos().setVisible(true); // abre uma tela de cadastro
    }//GEN-LAST:event_btnOutroPedidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaFinal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOutroPedido;
    private javax.swing.JLabel imagemFinal;
    private javax.swing.JLabel imagemFundo;
    private javax.swing.JLabel msgFinal;
    // End of variables declaration//GEN-END:variables
}
