
import Codigo.BaseCadastral;
import Codigo.Bebida;
import Codigo.Carrinho;
import Codigo.Cliente;
import Codigo.Pizza;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Bianca
 */
public class TelaConfirmacao extends javax.swing.JFrame {

    /**
     * Creates new form TelaConfirmacao
     */
    public TelaConfirmacao() {
        initComponents();
        
        // SETANDO CAMPOS EDITÁVEIS E NÃO EDITÁVEIS
        campoAdicionais.setEditable(false);
        campoBorda.setEditable(false);
        campoCidade.setEditable(true);
        campoComplemento.setEditable(true);
        campoEndereco.setEditable(true);
        campoFone2.setEditable(true);
        campoNome.setEditable(true);
        campoNumero.setEditable(true);
        campoPrecoTotal.setEditable(false);
        campoSabores.setEditable(false);
        campoTamanho.setEditable(false);
        campoTelefone1.setEditable(true);
        campoObservacoes.setEditable(false);
        campoBebida.setEditable(false);
        campoFormaPagamento.setEditable(false);
        campoBairro.setEditable(true);
        
        campoBorda.setText(Pizza.getInstance().getTipoBorda());
        campoTamanho.setText(Pizza.getInstance().getTamanho());
        
        for(int i = 0; i < Pizza.getInstance().getSabores().size(); i++)
        {
            campoSabores.setText(campoSabores.getText() + Pizza.getInstance().getSabores().get(i).getNome() + ";");
        }
        
        
        for(int i = 0; i < Pizza.getInstance().getAdicionais().size(); i++)
        {
            campoAdicionais.setText(campoAdicionais.getText() + Pizza.getInstance().getAdicionais().get(i).getNome() + ";");
        }
        
        campoPrecoTotal.setText("R$" + Integer.toString(Carrinho.getInstance().getPrecoTotal()) + ",00");
        campoObservacoes.setText(Pizza.getInstance().getObservacoes());
        campoBebida.setText(Bebida.getInstance().getNome());
        campoFormaPagamento.setText(Carrinho.getInstance().getPagamento());
        
        // Caso o usuário tenha logado com usuário e senha os campos já irão ser preenchidos automaticamente
        if(BaseCadastral.getInstance().getUltimoLogin() != null) 
        {
            
            for(Cliente c : BaseCadastral.getInstance().getCadastros())
            {
                if(BaseCadastral.getInstance().getUltimoLogin().equals(c.getLogin()))
                {
                    campoNome.setText(c.getNome());
                    campoCidade.setText(c.getCidade());
                    campoBairro.setText(c.getBairro());
                    campoComplemento.setText(c.getComplemento());
                    campoEndereco.setText(c.getRua());
                    campoTelefone1.setText(c.getFone1());
                    campoNumero.setText(Integer.toString(c.getNumeroCasa()));
                    
                }
                
            }
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        infTela = new javax.swing.JLabel();
        campoTamanho = new javax.swing.JTextField();
        infSabores = new javax.swing.JLabel();
        campoSabores = new javax.swing.JTextField();
        infComplemento = new javax.swing.JLabel();
        infTamanho = new javax.swing.JLabel();
        campoPrecoTotal = new javax.swing.JTextField();
        infObservacoes = new javax.swing.JLabel();
        campoEndereco = new javax.swing.JTextField();
        infBebida = new javax.swing.JLabel();
        campoBorda = new javax.swing.JTextField();
        infBorda = new javax.swing.JLabel();
        infNome = new javax.swing.JLabel();
        campoAdicionais = new javax.swing.JTextField();
        campoNumero = new javax.swing.JTextField();
        infNumero = new javax.swing.JLabel();
        campoComplemento = new javax.swing.JTextField();
        infCidade = new javax.swing.JLabel();
        campoNome = new javax.swing.JTextField();
        infDadosEndereco = new javax.swing.JLabel();
        campoCidade = new javax.swing.JTextField();
        infTelefone2 = new javax.swing.JLabel();
        campoTelefone1 = new javax.swing.JTextField();
        infTelefone1 = new javax.swing.JLabel();
        campoFone2 = new javax.swing.JTextField();
        btnConfirmar = new javax.swing.JButton();
        infAdicionais = new javax.swing.JLabel();
        campoObservacoes = new javax.swing.JTextField();
        infBairro = new javax.swing.JLabel();
        infFormaPagamento = new javax.swing.JLabel();
        campoBebida = new javax.swing.JTextField();
        infPrecoTotal = new javax.swing.JLabel();
        campoFormaPagamento = new javax.swing.JTextField();
        infEndereco = new javax.swing.JLabel();
        campoBairro = new javax.swing.JTextField();
        infDadosEndereco2 = new javax.swing.JLabel();
        imagemFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        infTela.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        infTela.setText("Confirmação do pedido");
        getContentPane().add(infTela);
        infTela.setBounds(280, 40, 240, 22);

        campoTamanho.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(campoTamanho);
        campoTamanho.setBounds(130, 110, 100, 30);

        infSabores.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        infSabores.setText("Sabores:");
        getContentPane().add(infSabores);
        infSabores.setBounds(250, 110, 80, 30);

        campoSabores.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(campoSabores);
        campoSabores.setBounds(320, 110, 370, 30);

        infComplemento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        infComplemento.setText("Complemento:");
        getContentPane().add(infComplemento);
        infComplemento.setBounds(450, 430, 110, 30);

        infTamanho.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        infTamanho.setText("Tamanho:");
        getContentPane().add(infTamanho);
        infTamanho.setBounds(50, 110, 70, 30);

        campoPrecoTotal.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(campoPrecoTotal);
        campoPrecoTotal.setBounds(130, 280, 90, 30);

        infObservacoes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        infObservacoes.setText("Observações:");
        getContentPane().add(infObservacoes);
        infObservacoes.setBounds(260, 220, 100, 30);
        getContentPane().add(campoEndereco);
        campoEndereco.setBounds(130, 380, 340, 30);

        infBebida.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        infBebida.setText("Bebida:");
        getContentPane().add(infBebida);
        infBebida.setBounds(70, 220, 80, 30);

        campoBorda.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(campoBorda);
        campoBorda.setBounds(130, 160, 90, 30);

        infBorda.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        infBorda.setText("Borda:");
        getContentPane().add(infBorda);
        infBorda.setBounds(70, 160, 50, 30);

        infNome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        infNome.setText("*Nome:");
        getContentPane().add(infNome);
        infNome.setBounds(70, 330, 60, 30);

        campoAdicionais.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(campoAdicionais);
        campoAdicionais.setBounds(340, 160, 350, 30);
        getContentPane().add(campoNumero);
        campoNumero.setBounds(370, 430, 50, 30);

        infNumero.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        infNumero.setText("*Nº:");
        getContentPane().add(infNumero);
        infNumero.setBounds(330, 430, 30, 30);
        getContentPane().add(campoComplemento);
        campoComplemento.setBounds(550, 430, 140, 30);

        infCidade.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        infCidade.setText("*Cidade:");
        getContentPane().add(infCidade);
        infCidade.setBounds(490, 380, 80, 30);
        getContentPane().add(campoNome);
        campoNome.setBounds(130, 330, 90, 30);

        infDadosEndereco.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        infDadosEndereco.setForeground(new java.awt.Color(0, 153, 0));
        infDadosEndereco.setText("Obs: Preencha os campos em branco caso tenha logado sem cadastro");
        getContentPane().add(infDadosEndereco);
        infDadosEndereco.setBounds(60, 480, 450, 30);
        getContentPane().add(campoCidade);
        campoCidade.setBounds(550, 380, 140, 30);

        infTelefone2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        infTelefone2.setText("Fone 2:");
        getContentPane().add(infTelefone2);
        infTelefone2.setBounds(440, 330, 60, 30);
        getContentPane().add(campoTelefone1);
        campoTelefone1.setBounds(290, 330, 120, 30);

        infTelefone1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        infTelefone1.setText("*Fone 1:");
        getContentPane().add(infTelefone1);
        infTelefone1.setBounds(230, 330, 80, 30);
        getContentPane().add(campoFone2);
        campoFone2.setBounds(500, 330, 130, 30);

        btnConfirmar.setText("Confirmar pedido");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });
        getContentPane().add(btnConfirmar);
        btnConfirmar.setBounds(570, 480, 150, 30);

        infAdicionais.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        infAdicionais.setText("Adicionais:");
        getContentPane().add(infAdicionais);
        infAdicionais.setBounds(260, 160, 80, 30);

        campoObservacoes.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(campoObservacoes);
        campoObservacoes.setBounds(350, 220, 340, 30);

        infBairro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        infBairro.setText("*Bairro:");
        getContentPane().add(infBairro);
        infBairro.setBounds(70, 430, 90, 30);

        infFormaPagamento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        infFormaPagamento.setText("Forma de pagamento:");
        getContentPane().add(infFormaPagamento);
        infFormaPagamento.setBounds(260, 280, 150, 30);

        campoBebida.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(campoBebida);
        campoBebida.setBounds(130, 220, 110, 30);

        infPrecoTotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        infPrecoTotal.setText("Preco Total:");
        getContentPane().add(infPrecoTotal);
        infPrecoTotal.setBounds(40, 280, 90, 30);

        campoFormaPagamento.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(campoFormaPagamento);
        campoFormaPagamento.setBounds(400, 280, 290, 30);

        infEndereco.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        infEndereco.setText("*Endereço:");
        getContentPane().add(infEndereco);
        infEndereco.setBounds(50, 380, 90, 30);
        getContentPane().add(campoBairro);
        campoBairro.setBounds(130, 430, 160, 30);

        infDadosEndereco2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        infDadosEndereco2.setForeground(new java.awt.Color(0, 153, 0));
        infDadosEndereco2.setText("* Campos obrigatórios");
        getContentPane().add(infDadosEndereco2);
        infDadosEndereco2.setBounds(60, 520, 150, 15);

        imagemFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo.fw.png"))); // NOI18N
        imagemFundo.setText("jLabel1");
        getContentPane().add(imagemFundo);
        imagemFundo.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        
        if(campoNome.getText().equals("") || 
           campoTelefone1.getText().equals("") ||
           campoEndereco.getText().equals("") ||
           campoCidade.getText().equals("") ||
           campoBairro.getText().equals("") ||
           campoNumero.getText().equals(""))
                JOptionPane.showMessageDialog(null, "Preencha todos os campos obrigatórios");
        
        else
        {
            dispose();
            new TelaFinal().setVisible(true);            
        }

    }//GEN-LAST:event_btnConfirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaConfirmacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaConfirmacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaConfirmacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaConfirmacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaConfirmacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JTextField campoAdicionais;
    private javax.swing.JTextField campoBairro;
    private javax.swing.JTextField campoBebida;
    private javax.swing.JTextField campoBorda;
    private javax.swing.JTextField campoCidade;
    private javax.swing.JTextField campoComplemento;
    private javax.swing.JTextField campoEndereco;
    private javax.swing.JTextField campoFone2;
    private javax.swing.JTextField campoFormaPagamento;
    private javax.swing.JTextField campoNome;
    private javax.swing.JTextField campoNumero;
    private javax.swing.JTextField campoObservacoes;
    private javax.swing.JTextField campoPrecoTotal;
    private javax.swing.JTextField campoSabores;
    private javax.swing.JTextField campoTamanho;
    private javax.swing.JTextField campoTelefone1;
    private javax.swing.JLabel imagemFundo;
    private javax.swing.JLabel infAdicionais;
    private javax.swing.JLabel infBairro;
    private javax.swing.JLabel infBebida;
    private javax.swing.JLabel infBorda;
    private javax.swing.JLabel infCidade;
    private javax.swing.JLabel infComplemento;
    private javax.swing.JLabel infDadosEndereco;
    private javax.swing.JLabel infDadosEndereco2;
    private javax.swing.JLabel infEndereco;
    private javax.swing.JLabel infFormaPagamento;
    private javax.swing.JLabel infNome;
    private javax.swing.JLabel infNumero;
    private javax.swing.JLabel infObservacoes;
    private javax.swing.JLabel infPrecoTotal;
    private javax.swing.JLabel infSabores;
    private javax.swing.JLabel infTamanho;
    private javax.swing.JLabel infTela;
    private javax.swing.JLabel infTelefone1;
    private javax.swing.JLabel infTelefone2;
    // End of variables declaration//GEN-END:variables
}
