
import Codigo.BaseCadastral;
import Codigo.Pizza;
import java.awt.Color;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Vitor
 */
public class TelaTamanhos extends javax.swing.JFrame {

    /**
     * Creates new form TelaTamanhos
     */
    public TelaTamanhos() {
        initComponents();
        getContentPane().setBackground(Color.white);
        
        if(BaseCadastral.getInstance().getUltimoLogin() == null) // Caso o usuário entre sem cadastro
            msgInicio.setText("Olá visitante");
        
        else
            msgInicio.setText("Olá " + BaseCadastral.getInstance().getUltimoLogin()); // Caso o usuário entre utilizando um cadastro
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        infTela = new javax.swing.JLabel();
        btnPequena = new javax.swing.JButton();
        btnMedia = new javax.swing.JButton();
        btnGrande = new javax.swing.JButton();
        btnFamilia = new javax.swing.JButton();
        msgInicio = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        imgFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        infTela.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        infTela.setText("Defina o tamanho da sua pizza:");
        getContentPane().add(infTela);
        infTela.setBounds(257, 42, 283, 22);

        btnPequena.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tamanhoPequena1.png"))); // NOI18N
        btnPequena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPequenaActionPerformed(evt);
            }
        });
        getContentPane().add(btnPequena);
        btnPequena.setBounds(151, 125, 191, 163);

        btnMedia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tamanhoMedia1.png"))); // NOI18N
        btnMedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMediaActionPerformed(evt);
            }
        });
        getContentPane().add(btnMedia);
        btnMedia.setBounds(151, 333, 191, 163);

        btnGrande.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tamanhoGrande1.png"))); // NOI18N
        btnGrande.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrandeActionPerformed(evt);
            }
        });
        getContentPane().add(btnGrande);
        btnGrande.setBounds(438, 125, 190, 163);

        btnFamilia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tamanhoFamilia1.png"))); // NOI18N
        btnFamilia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFamiliaActionPerformed(evt);
            }
        });
        getContentPane().add(btnFamilia);
        btnFamilia.setBounds(438, 333, 190, 163);

        msgInicio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(msgInicio);
        msgInicio.setBounds(20, 30, 140, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Preço inicia em R$ 4,00");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(160, 290, 130, 14);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Preço inicia em R$ 6,00");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(160, 500, 140, 14);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Preço inicia em R$ 8,00");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(450, 290, 170, 14);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Preço inicia em R$ 10,00");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(450, 500, 140, 14);

        imgFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo.fw.png"))); // NOI18N
        imgFundo.setText("jLabel2");
        getContentPane().add(imgFundo);
        imgFundo.setBounds(1, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPequenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPequenaActionPerformed
        Pizza.getInstance().setTamanho("Pequena");
        dispose();
        new TelaSaboresScrollbar().setVisible(true);
    }//GEN-LAST:event_btnPequenaActionPerformed

    private void btnGrandeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrandeActionPerformed
        Pizza.getInstance().setTamanho("Grande");
        dispose();
        new TelaSaboresScrollbar().setVisible(true);
    }//GEN-LAST:event_btnGrandeActionPerformed

    private void btnMediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMediaActionPerformed
        Pizza.getInstance().setTamanho("Média");
        dispose();
        new TelaSaboresScrollbar().setVisible(true);
    }//GEN-LAST:event_btnMediaActionPerformed

    private void btnFamiliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFamiliaActionPerformed
        Pizza.getInstance().setTamanho("Família");
        dispose();
        new TelaSaboresScrollbar().setVisible(true);
    }//GEN-LAST:event_btnFamiliaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaTamanhos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaTamanhos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaTamanhos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaTamanhos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaTamanhos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFamilia;
    private javax.swing.JButton btnGrande;
    private javax.swing.JButton btnMedia;
    private javax.swing.JButton btnPequena;
    private javax.swing.JLabel imgFundo;
    private javax.swing.JLabel infTela;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel msgInicio;
    // End of variables declaration//GEN-END:variables
}
