
import Codigo.EnumAdicional;
import Codigo.Pizza;
import Codigo.Bebida;
import Codigo.Carrinho;
import java.awt.Color;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Bianca
 */
public class TelaBebidas extends javax.swing.JFrame {

    /**
     * Creates new form TelaBebidas
     */
    public TelaBebidas() {
        initComponents();
        
        ButtonGroup bordas = new ButtonGroup();
        bordas.add(btnCatupiry);
        bordas.add(btnCheddar);
        bordas.add(btnChocolate);
        bordas.add(btnSemBorda);
        
        getContentPane().setBackground(Color.white);
        
        
        ButtonGroup bebidas = new ButtonGroup();
        bebidas.add(btnCocaCola);
        bebidas.add(btnSprite);
        bebidas.add(btnSemBebida);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        infBorda = new javax.swing.JLabel();
        infObsevacoes = new javax.swing.JLabel();
        btnAddAlho = new javax.swing.JCheckBox();
        btnAddCebola = new javax.swing.JCheckBox();
        btnAddCatupiry = new javax.swing.JCheckBox();
        btnAddBacon = new javax.swing.JCheckBox();
        btnSemBorda = new javax.swing.JRadioButton();
        btnCatupiry = new javax.swing.JRadioButton();
        btnCheddar = new javax.swing.JRadioButton();
        btnChocolate = new javax.swing.JRadioButton();
        imgCocaCola = new javax.swing.JLabel();
        imgSprite = new javax.swing.JLabel();
        campoObservacoes = new javax.swing.JTextField();
        infTela = new javax.swing.JLabel();
        btnConfirmar = new javax.swing.JButton();
        btnCocaCola = new javax.swing.JRadioButton();
        btnSprite = new javax.swing.JRadioButton();
        btnSemBebida = new javax.swing.JRadioButton();
        infAdicionais = new javax.swing.JLabel();
        imgFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        infBorda.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        infBorda.setText("Borda:");
        getContentPane().add(infBorda);
        infBorda.setBounds(600, 80, 70, 20);

        infObsevacoes.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        infObsevacoes.setText("Observações:");
        getContentPane().add(infObsevacoes);
        infObsevacoes.setBounds(600, 400, 120, 20);

        btnAddAlho.setText("+ Alho - R$ 2,00");
        btnAddAlho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAlhoActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddAlho);
        btnAddAlho.setBounds(600, 270, 130, 30);

        btnAddCebola.setText("+ Cebola - R$ 3,00");
        btnAddCebola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCebolaActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddCebola);
        btnAddCebola.setBounds(600, 300, 130, 30);

        btnAddCatupiry.setText("+ Catupiry - R$ 4,00");
        getContentPane().add(btnAddCatupiry);
        btnAddCatupiry.setBounds(600, 330, 130, 30);

        btnAddBacon.setText("+ Bacon - R$ 4,00");
        getContentPane().add(btnAddBacon);
        btnAddBacon.setBounds(600, 360, 130, 30);

        btnSemBorda.setText("Sem borda");
        getContentPane().add(btnSemBorda);
        btnSemBorda.setBounds(600, 200, 110, 23);

        btnCatupiry.setText("Catupiry");
        getContentPane().add(btnCatupiry);
        btnCatupiry.setBounds(600, 110, 110, 23);

        btnCheddar.setText("Cheddar");
        btnCheddar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheddarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCheddar);
        btnCheddar.setBounds(600, 140, 110, 23);

        btnChocolate.setText("Chocolate");
        btnChocolate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChocolateActionPerformed(evt);
            }
        });
        getContentPane().add(btnChocolate);
        btnChocolate.setBounds(600, 170, 110, 23);

        imgCocaCola.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        imgCocaCola.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/coca.png"))); // NOI18N
        imgCocaCola.setText("Coca-Cola 1,5L - R$ 7,00");
        getContentPane().add(imgCocaCola);
        imgCocaCola.setBounds(100, 200, 380, 160);

        imgSprite.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        imgSprite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sprite.png"))); // NOI18N
        imgSprite.setText("Sprite 2L - R$ 7,00");
        getContentPane().add(imgSprite);
        imgSprite.setBounds(110, 380, 330, 160);

        campoObservacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoObservacoesActionPerformed(evt);
            }
        });
        getContentPane().add(campoObservacoes);
        campoObservacoes.setBounds(600, 430, 160, 60);

        infTela.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        infTela.setText("Selecione sua bebida, borda e adicionais:");
        getContentPane().add(infTela);
        infTela.setBounds(30, 30, 410, 40);

        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });
        getContentPane().add(btnConfirmar);
        btnConfirmar.setBounds(600, 510, 120, 30);
        getContentPane().add(btnCocaCola);
        btnCocaCola.setBounds(50, 260, 21, 21);
        getContentPane().add(btnSprite);
        btnSprite.setBounds(50, 440, 20, 21);

        btnSemBebida.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnSemBebida.setText("Não desejo bebida");
        getContentPane().add(btnSemBebida);
        btnSemBebida.setBounds(50, 120, 210, 29);

        infAdicionais.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        infAdicionais.setText("Adicionais:");
        getContentPane().add(infAdicionais);
        infAdicionais.setBounds(600, 240, 110, 20);

        imgFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo.fw.png"))); // NOI18N
        imgFundo.setText("jLabel3");
        imgFundo.setMaximumSize(new java.awt.Dimension(800, 600));
        imgFundo.setMinimumSize(new java.awt.Dimension(800, 600));
        imgFundo.setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().add(imgFundo);
        imgFundo.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddAlhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAlhoActionPerformed
        
    }//GEN-LAST:event_btnAddAlhoActionPerformed

    private void btnCheddarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheddarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCheddarActionPerformed

    private void campoObservacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoObservacoesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoObservacoesActionPerformed

    private void btnChocolateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChocolateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnChocolateActionPerformed

    private void btnAddCebolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCebolaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddCebolaActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        
        
        if((!btnSemBebida.isSelected() && !btnCocaCola.isSelected() && !btnSprite.isSelected()) || (!btnCatupiry.isSelected() && !btnCheddar.isSelected() && !btnChocolate.isSelected() && !btnSemBorda.isSelected()))
            JOptionPane.showMessageDialog(null, "Você não selecionou alguma bebida ou a borda. Verifique e selecione.");
        
        else
        {
            if(btnCocaCola.isSelected())
            {
                Bebida.getInstance().setNome("Coca-cola");
                Bebida.getInstance().setPreco(7);
            }

            else if(btnSprite.isSelected())
            {
                Bebida.getInstance().setNome("Sprite");
                Bebida.getInstance().setPreco(7);
            }

            if(btnCatupiry.isSelected())
                Pizza.getInstance().setTipoBorda("Catupiry");

            else if(btnCheddar.isSelected())
                Pizza.getInstance().setTipoBorda("Cheddar");

            else if(btnChocolate.isSelected())
                Pizza.getInstance().setTipoBorda("Chocolate");

            else if(btnSemBorda.isSelected())
                Pizza.getInstance().setTipoBorda("Sem borda");
            
            if(btnAddAlho.isSelected())
            {
                Pizza.getInstance().getAdicionais().add(EnumAdicional.ALHO);
                Pizza.getInstance().setPreco(Pizza.getInstance().getPreco() + EnumAdicional.ALHO.getPreco());
            }
            
            if(btnAddBacon.isSelected())
            {
                Pizza.getInstance().getAdicionais().add(EnumAdicional.BACON);
                Pizza.getInstance().setPreco(Pizza.getInstance().getPreco() + EnumAdicional.BACON.getPreco());
            }
            
            if(btnAddCatupiry.isSelected())
            {
                Pizza.getInstance().getAdicionais().add(EnumAdicional.CATUPIRY);
                Pizza.getInstance().setPreco(Pizza.getInstance().getPreco() + EnumAdicional.CATUPIRY.getPreco());                
            }
            
            if(btnAddCebola.isSelected())
            {
                Pizza.getInstance().getAdicionais().add(EnumAdicional.CEBOLA);
                Pizza.getInstance().setPreco(Pizza.getInstance().getPreco() + EnumAdicional.CEBOLA.getPreco());                  
            }
            
            Pizza.getInstance().setObservacoes(campoObservacoes.getText());
            Carrinho.getInstance().setPrecoTotal(Pizza.getInstance().getPreco() + Bebida.getInstance().getPreco());

            dispose();
            new TelaPagamento().setVisible(true);
        }
               
        //System.out.println(Pizza.getInstance().getTipoBorda());
    }//GEN-LAST:event_btnConfirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaBebidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaBebidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaBebidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaBebidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaBebidas().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox btnAddAlho;
    private javax.swing.JCheckBox btnAddBacon;
    private javax.swing.JCheckBox btnAddCatupiry;
    private javax.swing.JCheckBox btnAddCebola;
    private javax.swing.JRadioButton btnCatupiry;
    private javax.swing.JRadioButton btnCheddar;
    private javax.swing.JRadioButton btnChocolate;
    private javax.swing.JRadioButton btnCocaCola;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JRadioButton btnSemBebida;
    private javax.swing.JRadioButton btnSemBorda;
    private javax.swing.JRadioButton btnSprite;
    private javax.swing.JTextField campoObservacoes;
    private javax.swing.JLabel imgCocaCola;
    private javax.swing.JLabel imgFundo;
    private javax.swing.JLabel imgSprite;
    private javax.swing.JLabel infAdicionais;
    private javax.swing.JLabel infBorda;
    private javax.swing.JLabel infObsevacoes;
    private javax.swing.JLabel infTela;
    // End of variables declaration//GEN-END:variables
}
