
import Codigo.BaseCadastral;
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Vitor
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
        
        getContentPane().setBackground(Color.white);
        
        ImageIcon imageIntro = new ImageIcon(TelaInicial.class.getResource("/imagens/pizzaiolo.fw.png"));
        Image img = imageIntro.getImage().getScaledInstance((80*3), (80*3), Image.SCALE_SMOOTH);
        imagemInicio.setIcon(new ImageIcon(img));
        
        
        /*ImageIcon imageIntro = new ImageIcon( getClass().getResource("./imagens/moto.png" ));
        Image image = imageIntro.getImage(); // transform it 
        Image newimg = image.getScaledInstance(50, 50,  java.awt.Image.SCALE_SMOOTH); // scale it the smooth way  
        imageIntro = new ImageIcon(newimg);*/
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloTela = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        infNovosUsuarios = new javax.swing.JLabel();
        labelLogin = new javax.swing.JLabel();
        labelSenha = new javax.swing.JLabel();
        campoLogin = new javax.swing.JTextField();
        campoSenha = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        btnSemCadastro = new javax.swing.JButton();
        imagemInicio = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        tituloTela.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tituloTela.setText("Encomenda de pizzas online");
        getContentPane().add(tituloTela);
        tituloTela.setBounds(250, 0, 253, 40);

        btnCadastrar.setText("Criar cadastro");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrar);
        btnCadastrar.setBounds(52, 377, 136, 57);

        infNovosUsuarios.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        infNovosUsuarios.setText("É novo por aqui?");
        getContentPane().add(infNovosUsuarios);
        infNovosUsuarios.setBounds(52, 338, 180, 28);

        labelLogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelLogin.setText("Login:");
        getContentPane().add(labelLogin);
        labelLogin.setBounds(480, 370, 50, 23);

        labelSenha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelSenha.setText("Senha:");
        getContentPane().add(labelSenha);
        labelSenha.setBounds(480, 420, 60, 14);

        campoLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoLoginActionPerformed(evt);
            }
        });
        getContentPane().add(campoLogin);
        campoLogin.setBounds(540, 370, 190, 30);
        getContentPane().add(campoSenha);
        campoSenha.setBounds(540, 410, 190, 30);

        btnLogin.setText("Entrar");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin);
        btnLogin.setBounds(592, 452, 63, 23);

        btnSemCadastro.setText("Acessar sem cadastro");
        btnSemCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSemCadastroActionPerformed(evt);
            }
        });
        getContentPane().add(btnSemCadastro);
        btnSemCadastro.setBounds(291, 519, 170, 23);
        getContentPane().add(imagemInicio);
        imagemInicio.setBounds(270, 70, 270, 270);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo1.fw.png"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        dispose(); // fecha a tela atual
        new TelaCadastro().setVisible(true); // abre uma tela de cadastro
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
       
        
        if(BaseCadastral.getInstance().verificaCadastro(campoLogin.getText(), campoSenha.getText()))
        {
            JOptionPane.showMessageDialog(null, "Bem vindo!");
            BaseCadastral.getInstance().setUltimoLogin(campoLogin.getText());
            dispose();
            new TelaTamanhos().setVisible(true); 
        }
        
        else
            JOptionPane.showMessageDialog(null, "Dados inválidos");
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnSemCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSemCadastroActionPerformed
        BaseCadastral.getInstance();
        dispose();
        new TelaTamanhos().setVisible(true);        
    }//GEN-LAST:event_btnSemCadastroActionPerformed

    private void campoLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnSemCadastro;
    private javax.swing.JTextField campoLogin;
    private javax.swing.JPasswordField campoSenha;
    private javax.swing.JLabel imagemInicio;
    private javax.swing.JLabel infNovosUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelLogin;
    private javax.swing.JLabel labelSenha;
    private javax.swing.JLabel tituloTela;
    // End of variables declaration//GEN-END:variables
}
