
import Codigo.Carrinho;
import java.awt.Color;
import javax.swing.ButtonGroup;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Bianca
 */
public class TelaPagamento extends javax.swing.JFrame {

    /**
     * Creates new form TelaPagamento
     */
    public TelaPagamento() {
        initComponents();
        
        ButtonGroup pagamentos = new ButtonGroup();
        pagamentos.add(btnDinheiro);
        pagamentos.add(btnMasterCard);
        pagamentos.add(btnVisa);
        pagamentos.add(btnElo);
        pagamentos.add(btnSodexo);
        
        getContentPane().setBackground(Color.white);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        infTela = new javax.swing.JLabel();
        btnDinheiro = new javax.swing.JRadioButton();
        btnMasterCard = new javax.swing.JRadioButton();
        btnVisa = new javax.swing.JRadioButton();
        btnElo = new javax.swing.JRadioButton();
        btnSodexo = new javax.swing.JRadioButton();
        dinheiro = new javax.swing.JLabel();
        mastercard = new javax.swing.JLabel();
        visa = new javax.swing.JLabel();
        elo = new javax.swing.JLabel();
        sodexo = new javax.swing.JLabel();
        btnConfirmaPag = new javax.swing.JButton();
        imgFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);

        infTela.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        infTela.setText("Informe a forma de pagamento:");
        getContentPane().add(infTela);
        infTela.setBounds(28, 39, 299, 27);

        btnDinheiro.setBorder(new javax.swing.border.MatteBorder(null));
        btnDinheiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDinheiroActionPerformed(evt);
            }
        });
        getContentPane().add(btnDinheiro);
        btnDinheiro.setBounds(304, 130, 15, 15);

        btnMasterCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasterCardActionPerformed(evt);
            }
        });
        getContentPane().add(btnMasterCard);
        btnMasterCard.setBounds(304, 252, 21, 21);

        btnVisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisaActionPerformed(evt);
            }
        });
        getContentPane().add(btnVisa);
        btnVisa.setBounds(521, 130, 21, 21);

        btnElo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEloActionPerformed(evt);
            }
        });
        getContentPane().add(btnElo);
        btnElo.setBounds(521, 252, 21, 21);

        btnSodexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSodexoActionPerformed(evt);
            }
        });
        getContentPane().add(btnSodexo);
        btnSodexo.setBounds(304, 378, 21, 21);

        dinheiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/dinheiro.fw.png"))); // NOI18N
        getContentPane().add(dinheiro);
        dinheiro.setBounds(93, 108, 128, 85);

        mastercard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/master.fw.png"))); // NOI18N
        mastercard.setText("jLabel3");
        getContentPane().add(mastercard);
        mastercard.setBounds(93, 211, 122, 89);

        visa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/visa.fw.png"))); // NOI18N
        getContentPane().add(visa);
        visa.setBounds(561, 108, 125, 85);

        elo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/eloo.png"))); // NOI18N
        getContentPane().add(elo);
        elo.setBounds(561, 211, 146, 73);

        sodexo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sodexo.fw.png"))); // NOI18N
        getContentPane().add(sodexo);
        sodexo.setBounds(93, 338, 142, 81);

        btnConfirmaPag.setText("Confirmar forma de pagamento");
        btnConfirmaPag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmaPagActionPerformed(evt);
            }
        });
        getContentPane().add(btnConfirmaPag);
        btnConfirmaPag.setBounds(490, 370, 220, 30);

        imgFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundonew.fw.png"))); // NOI18N
        getContentPane().add(imgFundo);
        imgFundo.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDinheiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDinheiroActionPerformed
        Carrinho.getInstance().setPagamento("Dinheiro");
    }//GEN-LAST:event_btnDinheiroActionPerformed

    private void btnConfirmaPagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmaPagActionPerformed
        dispose();
        new TelaConfirmacao().setVisible(true);
    }//GEN-LAST:event_btnConfirmaPagActionPerformed

    private void btnMasterCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasterCardActionPerformed
        Carrinho.getInstance().setPagamento("MasterCard");
    }//GEN-LAST:event_btnMasterCardActionPerformed

    private void btnSodexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSodexoActionPerformed
        Carrinho.getInstance().setPagamento("Sodexo");
    }//GEN-LAST:event_btnSodexoActionPerformed

    private void btnVisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisaActionPerformed
        Carrinho.getInstance().setPagamento("Visa");
    }//GEN-LAST:event_btnVisaActionPerformed

    private void btnEloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEloActionPerformed
        Carrinho.getInstance().setPagamento("Elo");
    }//GEN-LAST:event_btnEloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPagamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmaPag;
    private javax.swing.JRadioButton btnDinheiro;
    private javax.swing.JRadioButton btnElo;
    private javax.swing.JRadioButton btnMasterCard;
    private javax.swing.JRadioButton btnSodexo;
    private javax.swing.JRadioButton btnVisa;
    private javax.swing.JLabel dinheiro;
    private javax.swing.JLabel elo;
    private javax.swing.JLabel imgFundo;
    private javax.swing.JLabel infTela;
    private javax.swing.JLabel mastercard;
    private javax.swing.JLabel sodexo;
    private javax.swing.JLabel visa;
    // End of variables declaration//GEN-END:variables
}
